#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := rgb_matrix.cpp

# header files in this project
HEADERS := graphics_drawer.hpp image_invert.hpp image_rainbow.hpp rainbow.hpp rainbow_font.hpp rgb_matrix.hpp rgb_matrix_part.hpp rgb_matrix_port.hpp rgb_pins.hpp updating_drawable.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/makefile.due
